import type { CropVariety } from "@/data/mock/crop-overview";

export type PaddyEcology =
  | "irrigated"
  | "rainfed"
  | "usar"
  | "flood"
  | "dsr"
  | "basmati"
  | "common";

export type GrainType = "basmati" | "coarse" | "fine" | "medium";

export interface MarketVarietyRec extends CropVariety {
  /** States where this variety sells / grows well */
  states: string[];
  marketNote: string;
  /** Public/govt breeding vs private hybrid seed */
  source: "govt" | "private";
  /** Paddy ecology niche (irrigated, rainfed, usar, etc.) */
  ecology?: PaddyEcology;
  /** Typical crop duration in days */
  durationDays?: { min: number; max: number };
  /** Grain market class */
  grainType?: GrainType;
  /** क्षेत्र / स्थिति — किसान भाषा */
  regionHi?: string;
  /** अनुमानित उपज (एकड़) */
  yieldHi?: string;
  /** खास बात / खेती टिप */
  tipHi?: string;
}

const VARIETIES_BY_CROP: Record<string, MarketVarietyRec[]> = {
  paddy: [
    {
      name: "पूसा बासमती 1121",
      trait: "दुनिया की सबसे लंबी बासमती; पकाने पर दाना दोगुना लंबा",
      season: "खरीफ",
      states: ["Punjab","Haryana","Uttar Pradesh"],
      source: "govt",
      marketNote: "एक्सपोर्ट क्वालिटी — बाजार में सबसे ज्यादा दाम",
      ecology: "basmati",
      durationDays: { min: 140, max: 145 },
      grainType: "basmati",
      regionHi: "सिंचित क्षेत्र — पंजाब, हरियाणा, पश्चिमी उत्तर प्रदेश",
      yieldHi: "16–18 कुंटल/एकड़",
      tipHi: "यूरिया ज्यादा न डालें — पौधा लंबा होकर गिर सकता है और दाना पतला रह जाएगा।",
    },
    {
      name: "स्वर्ण सब-1 / CR धान 801",
      trait: "बाढ़ सहनशील — 10–14 दिन डूबने पर भी फसल बचती है",
      season: "खरीफ",
      states: ["Uttar Pradesh","Bihar","West Bengal","Odisha"],
      source: "govt",
      marketNote: "पूर्वी बाढ़ क्षेत्रों की भरोसेमंद किस्म",
      ecology: "flood",
      durationDays: { min: 140, max: 150 },
      grainType: "coarse",
      regionHi: "बाढ़/जलभराव — पूर्वी यू.पी., बिहार, पश्चिम बंगाल, ओडिशा",
      yieldHi: "22–25 कुंटल/एकड़",
      tipHi: "बाढ़ के बाद पानी निकलते ही हल्का यूरिया डालें — पौधा जल्दी रिकवर करता है।",
    },
    {
      name: "अराइज 6444 गोल्ड (बायर)",
      trait: "BLB झुलसा प्रतिरोधी; मजबूत तना — तेज हवा में नहीं गिरता",
      season: "खरीफ",
      states: ["Uttar Pradesh","Bihar","Madhya Pradesh","Maharashtra","Haryana","Punjab"],
      source: "private",
      marketNote: "भारत की सबसे ज्यादा बिकने वाली हाइब्रिड में से एक",
      ecology: "irrigated",
      durationDays: { min: 130, max: 135 },
      grainType: "medium",
      regionHi: "पूरे भारत — सिंचित व आंशिक सिंचित क्षेत्र",
      yieldHi: "28–30 कुंटल/एकड़",
      tipHi: "कल्ले ज्यादा निकलते हैं — रोपाई में दूरी 20×20 सेमी रखें।",
    },
    {
      name: "CSR 36 / CSR 43",
      trait: "ऊसर/लवणीय मिट्टी में सामान्य किस्म से 30–40% ज्यादा पैदावार",
      season: "खरीफ",
      states: ["Uttar Pradesh","Haryana","Punjab","Rajasthan"],
      source: "govt",
      marketNote: "नमकीन/ऊसर भूमि के लिए प्रमाणित विकल्प",
      ecology: "usar",
      durationDays: { min: 110, max: 140 },
      grainType: "medium",
      regionHi: "लवणीय/क्षारीय ऊसर भूमि",
      yieldHi: "सामान्य किस्म से 30–40% अधिक",
      tipHi: "CSR 36 ≈ 135–140 दिन; CSR 43 ≈ 110–115 दिन (अगेती)।",
    },
    {
      name: "पीआर 126",
      trait: "कम पानी, कम समय — गेहूं की अगेती बुवाई के लिए खेत जल्दी खाली",
      season: "खरीफ",
      states: ["Punjab","Haryana"],
      source: "govt",
      marketNote: "DSR और कम पानी वाले क्षेत्रों की पसंद",
      ecology: "dsr",
      durationDays: { min: 120, max: 125 },
      grainType: "medium",
      regionHi: "सीधी बिजाई (DSR) और कम पानी वाले क्षेत्र",
      yieldHi: "अच्छी औसत उपज — कम अवधि में",
      tipHi: "नर्सरी से कटाई तक मात्र 120–125 दिन — गेहूं चक्र में फायदेमंद।",
    },
  ],
  wheat: [
    {
      name: "HD 2967 (पूसा मालवीय)",
      trait: "भारत की सबसे लोकप्रिय किस्म; पीला रतुआ सहनशील",
      season: "रबी",
      states: ["Punjab","Haryana","Uttar Pradesh","Madhya Pradesh"],
      source: "govt",
      marketNote: "MSP आवक में सबसे आम",
      durationDays: { min: 140, max: 145 },
      regionHi: "उत्तर-पश्चिम — सिंचित, समय पर बुवाई",
      yieldHi: "22–25 कुंटल/एकड़",
      tipHi: "पिछेती बुवाई में न लगाएँ — नवंबर में समय पर बुवाई पर ही अच्छी उपज।",
    },
    {
      name: "DBW 187 (करण वंदना)",
      trait: "उच्च उपज; ब्लास्ट व रतुआ प्रतिरोधी; प्रोटीन 12%+",
      season: "रबी",
      states: ["Punjab","Haryana","Uttar Pradesh","Bihar"],
      source: "govt",
      marketNote: "उत्तर मैदानों में ऊँची पैदावार वाली किस्म",
      durationDays: { min: 145, max: 150 },
      regionHi: "उत्तर-पूर्वी व उत्तर-पश्चिम मैदान",
      yieldHi: "26–28 कुंटल/एकड़ (संभावना 28–30 तक)",
      tipHi: "बाली निकलते और दाना भरते समय खेत में नमी जरूर रखें — सूखा न पड़ने दें।",
    },
    {
      name: "HD 3086 (पूसा गौतमी)",
      trait: "गर्मी सहन — पकते समय तापमान बढ़े तो दाना नहीं सिकुड़ता; रोटी उत्तम",
      season: "रबी",
      states: ["Punjab","Haryana","Uttar Pradesh","Bihar"],
      source: "govt",
      marketNote: "चापाती क्वालिटी के लिए उत्तम",
      durationDays: { min: 135, max: 140 },
      regionHi: "सिंचित व गर्मी (हीट स्ट्रेस) वाले क्षेत्र",
      yieldHi: "अच्छी औसत उपज",
      tipHi: "देर रबी/गर्म अंत वाले क्षेत्रों के लिए सुरक्षित विकल्प।",
    },
    {
      name: "KRL 210 / KRL 213",
      trait: "ऊसर व खारे पानी में भी पैदावार देती है",
      season: "रबी",
      states: ["Uttar Pradesh","Haryana","Rajasthan","Punjab"],
      source: "govt",
      marketNote: "क्षारीय मिट्टी के लिए विशेष किस्म",
      durationDays: { min: 135, max: 140 },
      regionHi: "क्षारीय/लवणीय मिट्टी — pH 8.5–9.3 तक",
      yieldHi: "15–18 कुंटल/एकड़ (ऊसर में)",
      tipHi: "सामान्य किस्म जहाँ फेल हो, वहाँ KRL श्रृंखला आज़माएँ।",
    },
    {
      name: "HI 1605 (पूसा उजाला) / HI 8759 (पूसा तेजस)",
      trait: "कम सिंचाई (1–2 पानी) में अच्छा प्रदर्शन; तेजस ड्यूरम/कटिया",
      season: "रबी",
      states: ["Madhya Pradesh","Rajasthan","Gujarat"],
      source: "govt",
      marketNote: "मध्य भारत वर्षा आधारित क्षेत्रों की पसंद",
      regionHi: "मध्य भारत — वर्षा आधारित या सीमित सिंचाई",
      yieldHi: "सीमित पानी में स्थिर उपज",
      tipHi: "पूसा तेजस सूजी/पास्ता वाला ड्यूरम गेहूं है।",
    },
  ],
  tomato: [
    {
      name: "सेमिनिस अभिलाष / सिंजेंटा अभिनव",
      trait: "कड़ा, गहरा लाल, वर्गाकार-गोल — लंबी ढुलाई व शेल्फ लाइफ",
      season: "खरीफ / रबी / जायद",
      states: ["Maharashtra","Karnataka","Andhra Pradesh","Uttar Pradesh","Madhya Pradesh","Gujarat"],
      source: "private",
      marketNote: "दूर मंडी भेजने के लिए बेस्ट",
      regionHi: "ऑल इंडिया — तीनों मौसम",
      yieldHi: "30–35 टन/एकड़",
      tipHi: "मचान (स्टेकिंग) + मल्चिंग पेपर लगाएँ — फल नहीं सड़ते, उपज लगभग दोगुनी।",
    },
    {
      name: "अर्क रक्षक (IIHR)",
      trait: "त्रिस्तरीय रोग प्रतिरोध — लीफ कर्ल, बैक्टीरियल विल्ट, अर्ली ब्लाइट",
      season: "खरीफ / रबी",
      states: ["Karnataka","Andhra Pradesh","Tamil Nadu","Maharashtra","Madhya Pradesh"],
      source: "govt",
      marketNote: "दवा खर्च बचाने वाली सरकारी हाइब्रिड",
      regionHi: "सिंचित + मल्चिंग/ड्रिप वाली खेती",
      yieldHi: "35–40 टन/एकड़",
      tipHi: "तीन बीमारियों से बचाव — फफूंदनाशक/कीटनाशक खर्च काफी बचता है।",
    },
    {
      name: "US 440",
      trait: "अगेती तुड़ाई; चमकदार फल — मंडी में तुरंत बिकते हैं",
      season: "खरीफ / रबी",
      states: ["Karnataka","Andhra Pradesh","Madhya Pradesh","Maharashtra"],
      source: "private",
      marketNote: "दक्षिण व मध्य भारत में प्रसिद्ध",
      regionHi: "दक्षिण व मध्य भारत",
      yieldHi: "अच्छी व्यापारिक उपज",
      tipHi: "बाजार में जल्दी आना हो तो अगेती किस्म चुनें।",
    },
  ],
  soybean: [
    {
      name: "JS 335",
      trait: "सबसे पुरानी ऑल-राउंडर; विपरीत मौसम में भी स्थिर उत्पादन",
      season: "खरीफ",
      states: ["Madhya Pradesh","Maharashtra","Rajasthan"],
      source: "govt",
      marketNote: "भारत में सबसे ज्यादा बोई जाने वाली सोयाबीन",
      durationDays: { min: 95, max: 100 },
      regionHi: "म.प्र., महाराष्ट्र, राजस्थान — सभी मिट्टियाँ",
      yieldHi: "8–10 कुंटल/एकड़",
      tipHi: "बीज दर 30–32 किग्रा/एकड़ रखें — ज्यादा घने पौधे पर फूल झड़ते हैं।",
    },
    {
      name: "JS 95-60",
      trait: "अगेती — 80–85 दिन में तैयार; अगली फसल समय पर",
      season: "खरीफ",
      states: ["Madhya Pradesh","Rajasthan","Maharashtra"],
      source: "govt",
      marketNote: "कम बारिश/कम समय वाले क्षेत्रों के लिए",
      durationDays: { min: 80, max: 85 },
      regionHi: "कम बारिश या कम अवधि वाले क्षेत्र",
      yieldHi: "7–8 कुंटल/एकड़",
      tipHi: "बारिश जल्दी चली जाए तो भी उपज पर कम असर — जल्दी पकती है।",
    },
    {
      name: "JS 20-34 / NRC 138",
      trait: "सूखा सहन; छोटे पौधे — फसल नहीं गिरती; गर्डल बीटल क्षेत्र के लिए",
      season: "खरीफ",
      states: ["Madhya Pradesh","Maharashtra","Rajasthan"],
      source: "govt",
      marketNote: "सूखा प्रभावित क्षेत्रों की सुरक्षित किस्म",
      durationDays: { min: 88, max: 92 },
      regionHi: "सूखा / गर्डल बीटल–तना मक्खी प्रभावित क्षेत्र",
      yieldHi: "कम बारिश में स्थिर फलियाँ",
      tipHi: "कम बारिश में भी फलियाँ नहीं सूखतीं — छोटे पौधे, कम lodging।",
    },
  ],
  maize: [
    {
      name: "पायनियर 3355 / 1899",
      trait: "बड़ा भुट्टा, ऊपर तक दाना भरा; मजबूत तना — आंधी में नहीं गिरता",
      season: "खरीफ / रबी",
      states: ["Uttar Pradesh","Bihar","Madhya Pradesh","Rajasthan","Karnataka","Maharashtra"],
      source: "private",
      marketNote: "ऑल इंडिया लोकप्रिय हाइब्रिड",
      regionHi: "ऑल इंडिया — खरीफ व रबी",
      yieldHi: "30–35 कुंटल/एकड़",
      tipHi: "फॉल आर्मीवर्म दिखते ही पहली स्टेज में स्पिनटोराम या इमामेक्टिन का स्प्रे करें।",
    },
    {
      name: "DKC 9108 (बायर डेकाल्ब)",
      trait: "सूखा सहन — नमी कम होने पर भी दाना भरना जारी",
      season: "खरीफ",
      states: ["Rajasthan","Madhya Pradesh","Maharashtra","Gujarat"],
      source: "private",
      marketNote: "वर्षा आधारित/सूखा क्षेत्रों की पसंद",
      regionHi: "बारिश आधारित व सूखा प्रभावित क्षेत्र",
      yieldHi: "28–30 कुंटल/एकड़",
      tipHi: "सूखा सहन अच्छी है, पर टैसलिंग (जीरा आते समय) पानी जरूर दें — वरना दाना नहीं भरेगा।",
    },
    {
      name: "HQPM 1",
      trait: "उच्च प्रोटीन मक्का — लाइसीन व ट्रिप्टोफैन साधारण से दोगुना",
      season: "खरीफ / रबी",
      states: ["Bihar","Karnataka","Madhya Pradesh","Rajasthan","Uttar Pradesh"],
      source: "govt",
      marketNote: "पोल्ट्री फीड व खाद्य प्रसंस्करण के लिए",
      regionHi: "फीड, पशु आहार व प्रोसेसिंग",
      yieldHi: "अच्छी फीड ग्रेड उपज",
      tipHi: "पोल्ट्री/प्रोसेसिंग कॉन्ट्रैक्ट वाले किसानों के लिए खास।",
    },
  ],
  moongfali: [
    {
      name: "TG 37A (ट्रॉम्बे)",
      trait: "बड़े दाने, तेल 48–50%; गुच्छेदार — उखाड़ना आसान",
      season: "खरीफ / गर्मी",
      states: ["Rajasthan","Gujarat","Punjab"],
      source: "govt",
      marketNote: "उत्तर-पश्चिम की लोकप्रिय किस्म",
      durationDays: { min: 100, max: 105 },
      regionHi: "उत्तर व पश्चिमी भारत — राजस्थान, गुजरात, पंजाब",
      yieldHi: "10–12 कुंटल/एकड़",
      tipHi: "फूल आने के बाद कल्टीवेटर/खुरपी न चलाएँ — जमीन में जा रही सूइयाँ (पेग) टूट जाएँगी।",
    },
    {
      name: "कादिरी 6 (K-6)",
      trait: "सूखा सहन — कम बारिश में भी फली में दाना पूरा",
      season: "खरीफ",
      states: ["Andhra Pradesh","Karnataka","Tamil Nadu"],
      source: "govt",
      marketNote: "दक्षिण वर्षा आधारित क्षेत्रों की मुख्य किस्म",
      durationDays: { min: 100, max: 110 },
      regionHi: "आंध्र, कर्नाटक, तमिलनाडु — वर्षा आधारित",
      yieldHi: "8–10 कुंटल/एकड़",
      tipHi: "जिप्सम 100 किग्रा/एकड़ जरूर डालें — दाना पूरा भरता है, खाली फलियाँ (पॉप्स) कम।",
    },
    {
      name: "JL 24 (फुले प्रगति)",
      trait: "अगेती — 90–95 दिन; हल्की-मध्यम मिट्टी के लिए",
      season: "खरीफ",
      states: ["Maharashtra","Gujarat","Karnataka","Andhra Pradesh","Madhya Pradesh"],
      source: "govt",
      marketNote: "ऑल इंडिया प्रसिद्ध अगेती किस्म",
      durationDays: { min: 90, max: 95 },
      regionHi: "ऑल इंडिया — हल्की से मध्यम मिट्टी",
      yieldHi: "अच्छी अगेती उपज",
      tipHi: "कम समय में तैयार — अगली फसल के लिए खेत जल्दी खाली।",
    },
  ],
  chilli: [
    {
      name: "VNR 145",
      trait: "अत्यधिक तीखी, गहरा हरा; सूखने पर चमकदार लाल; लंबी तुड़ाई",
      season: "खरीफ / रबी",
      states: ["Andhra Pradesh","Telangana","Madhya Pradesh","Maharashtra","Uttar Pradesh"],
      source: "private",
      marketNote: "हरी मिर्च / ताजा बाजार — ऑल इंडिया",
      regionHi: "ताजा बाजार के लिए पूरे भारत",
      yieldHi: "15–20 टन/एकड़ (हरी मिर्च)",
      tipHi: "थ्रिप्स व सफेद मक्खी रोकने के लिए शुरू में येलो व ब्लू स्टिकी ट्रैप लगाएँ।",
    },
    {
      name: "सिंजेंटा 5531 / 7835",
      trait: "लीफ कर्ल (मुर्रा/चुर्रा) व थ्रिप्स सहन; ऊँची उत्पादन क्षमता",
      season: "खरीफ / रबी",
      states: ["Andhra Pradesh","Telangana","Madhya Pradesh","Maharashtra","Karnataka"],
      source: "private",
      marketNote: "वायरस प्रभावित क्षेत्रों की सुरक्षित हाइब्रिड",
      regionHi: "लीफ कर्ल वायरस प्रभावित क्षेत्र",
      yieldHi: "18–20 टन/एकड़",
      tipHi: "चुर्रा-मुर्रा बचाव — हर 10–15 दिन नीम तेल (1500 PPM) नियमित स्प्रे करें।",
    },
    {
      name: "पूसा ज्वाला",
      trait: "OP किस्म — कम बजट; झाड़ीदार पौधा, तीखापन तेज",
      season: "खरीफ / रबी",
      states: ["Uttar Pradesh","Bihar","Madhya Pradesh","Rajasthan","Haryana"],
      source: "govt",
      marketNote: "पारंपरिक किसानों की पहली पसंद",
      regionHi: "कम बजट ओपन-पॉलीनेटेड खेती",
      yieldHi: "मध्यम उपज — कम बीज खर्च",
      tipHi: "बीज खुद बचाकर अगले साल बो सकते हैं।",
    },
  ],
  cauliflower: [
    {
      name: "पूसा दीपाली",
      trait: "अगेती — गर्मी व नमी सहन; मध्यम, ठोस, सफेद फूल",
      season: "अगेती",
      states: ["Uttar Pradesh","Haryana","Punjab","Bihar","Madhya Pradesh"],
      source: "govt",
      marketNote: "अगेती मौसम — पूरे मैदानी भारत",
      durationDays: { min: 60, max: 70 },
      regionHi: "अगेती खेती — मैदानी क्षेत्र",
      yieldHi: "अच्छी अगेती उपज",
      tipHi: "रोपाई के 60–70 दिन में तैयार — गर्मी सहन अच्छी।",
    },
    {
      name: "सिंजेंटा 1522 / महिको मेधा",
      trait: "बर्फ जैसा सफेद, भारी ठोस; सेल्फ-ब्लांचिंग — धूप से पीला नहीं",
      season: "मध्य / पछेती",
      states: ["Uttar Pradesh","Haryana","Punjab","Maharashtra","Madhya Pradesh"],
      source: "private",
      marketNote: "दूर परिवहन के लिए बेस्ट",
      regionHi: "मध्य व पछेती — सिंचित क्षेत्र",
      yieldHi: "10–12 टन/एकड़",
      tipHi: "बोरॉन कमी से फूल भूराना/सड़ना — बोरेक्स (20%) स्प्रे जरूर करें।",
    },
    {
      name: "पूसा स्नोबॉल K-1",
      trait: "ठंड व पाला सहन; ठोस कसकर बंधा फूल; लंबे समय तरोताजा",
      season: "रबी",
      states: ["Uttar Pradesh","Haryana","Punjab","Himachal Pradesh","Bihar"],
      source: "govt",
      marketNote: "उत्तर भारत रबी की क्लासिक किस्म",
      durationDays: { min: 85, max: 95 },
      regionHi: "रबी ठंड — उत्तर भारत व पहाड़ी क्षेत्र",
      yieldHi: "12–15 टन/एकड़",
      tipHi: "नाइट्रोजन ज्यादा न दें — तना अंदर से खोखला (हॉलो स्टेम) हो सकता है।",
    },
  ],
  cucumber: [
    {
      name: "नामधारी NS 404",
      trait: "गहरा हरा, 18–22 सेमी, बिना कड़वाहट; ज्यादा शाखाएँ — ऊँची उपज",
      season: "गर्मी / बरसात",
      states: ["Uttar Pradesh","Haryana","Maharashtra","Karnataka","Madhya Pradesh"],
      source: "private",
      marketNote: "ओपन फील्ड — ऑल इंडिया",
      regionHi: "गर्मी व बरसात — ओपन फील्ड",
      yieldHi: "15–18 टन/एकड़",
      tipHi: "फल मक्खी से बचाव — फिरोमोन ट्रैप लगाना सबसे सस्ता और अच्छा उपाय।",
    },
    {
      name: "सेमिनिस मालिनी",
      trait: "अगेती तुड़ाई 40–45 दिन; डाउनी मिल्ड्यू व मोज़ेक सहन",
      season: "गर्मी / पॉलीहाउस",
      states: ["Haryana","Maharashtra","Karnataka","Uttar Pradesh"],
      source: "private",
      marketNote: "ओपन फील्ड व नेट/पॉलीहाउस दोनों",
      regionHi: "ओपन फील्ड व संरक्षित खेती",
      yieldHi: "18–20 टन/एकड़",
      tipHi: "हर 3–4 दिन तुड़ाई करें — बड़े फल छोड़ने से नए फूल/फल बंद हो जाते हैं।",
    },
    {
      name: "पूसा संयोग",
      trait: "गाइनोसियस — ज्यादा मादा फूल; हर गाँठ पर खीरा",
      season: "गर्मी / खरीफ",
      states: ["Uttar Pradesh","Madhya Pradesh","Haryana","Bihar"],
      source: "govt",
      marketNote: "उत्तर व मध्य भारत की सरकारी हाइब्रिड",
      regionHi: "उत्तर व मध्य भारत",
      yieldHi: "ऊँची फल संख्या",
      tipHi: "मादा फूल ज्यादा — सही परागण/पुरुष पौधे अनुपात रखें।",
    },
  ],
  brinjal: [
    {
      name: "वीएनआर 212",
      trait: "गोल-अंडाकार, गहरा बैंगनी चमकदार; काँटे रहित; छेदक सहिष्णु",
      season: "साल भर",
      states: ["Uttar Pradesh","Bihar","Maharashtra","Madhya Pradesh","West Bengal"],
      source: "private",
      marketNote: "ताजा बाजार व दूर भेजने के लिए",
      regionHi: "ऑल इंडिया",
      yieldHi: "25–30 टन/एकड़",
      tipHi: "तना/फल छेदक आए तो सूखी टहनियाँ व कीड़े वाले फल तोड़कर जमीन में दबा दें।",
    },
    {
      name: "महिको नवनीत / मयूरी",
      trait: "लंबे फल, गहरा बैंगनी, गुदेदार — भरता व सब्जी दोनों",
      season: "खरीफ / रबी",
      states: ["Uttar Pradesh","Madhya Pradesh","Bihar","Haryana"],
      source: "private",
      marketNote: "भरता मार्केट की माँग वाली किस्म",
      regionHi: "उत्तर व मध्य भारत",
      yieldHi: "20–25 टन/एकड़",
      tipHi: "उकठा बचाव — 2–3 साल टमाटर, मिर्च या आलू उसी खेत में न बोएँ।",
    },
    {
      name: "पूसा पर्पल क्लस्टर",
      trait: "गुच्छों में फल; बैक्टीरियल विल्ट अत्यधिक प्रतिरोधी",
      season: "खरीफ / रबी",
      states: ["Uttar Pradesh","Bihar","West Bengal","Odisha"],
      source: "govt",
      marketNote: "उकठा प्रभावित क्षेत्रों के लिए",
      regionHi: "जीवाणु उकठा प्रभावित क्षेत्र",
      yieldHi: "मध्यम-अच्छी उपज",
      tipHi: "विल्ट वाले खेतों में सबसे सुरक्षित सरकारी विकल्प।",
    },
  ],
  sugarcane: [
    {
      name: "Co 0238 (करण 4)",
      trait: "अगेती; शर्करा रिकवरी 12%+; बंपर पैदावार",
      season: "साल भर",
      states: ["Uttar Pradesh","Punjab","Haryana","Bihar"],
      source: "govt",
      marketNote: "उत्तर भारत में सबसे ज्यादा बोई जाने वाली",
      regionHi: "उत्तर भारत — यू.पी., पंजाब, हरियाणा, बिहार",
      yieldHi: "350–400 कुंटल/एकड़",
      tipHi: "रेड रॉट (लाल सड़न) का खतरा — सिर्फ स्वस्थ नए खेत से ही बीज (सेट) चुनें।",
    },
    {
      name: "Co 86032 (नयना)",
      trait: "सूखा सहन; पेड़ी में शानदार फुटाव व वजन",
      season: "साल भर",
      states: ["Maharashtra","Karnataka","Tamil Nadu","Madhya Pradesh"],
      source: "govt",
      marketNote: "दक्षिण व मध्य भारत मिलों की पसंद",
      regionHi: "दक्षिण व मध्य भारत",
      yieldHi: "300–350 कुंटल/एकड़",
      tipHi: "पेड़ी रखते समय ठूँठ की छिलाई करें और शुरुआती नाइट्रोजन थोड़ी बढ़ा दें।",
    },
    {
      name: "CoLK 94184 (वीरेंद्र) / Co 15023",
      trait: "जलभराव में तना नहीं सड़ता; रिकवरी बनी रहती है",
      season: "साल भर",
      states: ["Uttar Pradesh","Bihar","West Bengal"],
      source: "govt",
      marketNote: "बाढ़/जलभराव क्षेत्रों के लिए",
      regionHi: "जलभराव व बाढ़ प्रभावित क्षेत्र",
      yieldHi: "बाढ़ क्षेत्र में स्थिर रिकवरी",
      tipHi: "पानी में डूबे रहने पर भी तना सड़ने से बचता है।",
    },
  ],
  potato: [
    {
      name: "कुफरी पुखराज",
      trait: "अगेती 70–80 दिन; बड़े पीले कंद; अर्ली ब्लाइट सहन",
      season: "अगेती रबी",
      states: ["Uttar Pradesh","Bihar","West Bengal","Punjab","Haryana","Madhya Pradesh"],
      source: "govt",
      marketNote: "बाजार में सबसे पहले बिकने वाली",
      durationDays: { min: 70, max: 80 },
      regionHi: "अगेती फसल — ऑल इंडिया",
      yieldHi: "120–130 कुंटल/एकड़",
      tipHi: "जल्दी पकती है — अगेती झुलसा असर दिखने से पहले फसल तैयार।",
    },
    {
      name: "कुफरी ख्याति / कुफरी बहार",
      trait: "सफेद चिकनी त्वचा; कोल्ड स्टोरेज उत्तम; ऊँची उपज",
      season: "रबी",
      states: ["Uttar Pradesh","Haryana","Bihar","Punjab"],
      source: "govt",
      marketNote: "मुख्य रबी — उत्तर मैदान",
      durationDays: { min: 90, max: 100 },
      regionHi: "उत्तर भारत मैदानी — मुख्य रबी",
      yieldHi: "140–160 कुंटल/एकड़",
      tipHi: "मिट्टी चढ़ाते समय कंद धूप में न आएँ — हरा (ग्रीनिंग) होकर जहरीला हो जाता है।",
    },
    {
      name: "कुफरी चिप्सोना-3 / कुफरी फ्राइसोना",
      trait: "प्रोसेसिंग — ज्यादा ड्राई मैटर, कम रिड्यूसिंग शुगर; चिप्स काले नहीं",
      season: "रबी",
      states: ["Gujarat","Punjab","Uttar Pradesh","Madhya Pradesh"],
      source: "govt",
      marketNote: "चिप्स/वेफर इंडस्ट्री कॉन्ट्रैक्ट",
      regionHi: "प्रोसेसिंग इंडस्ट्री के लिए",
      yieldHi: "उद्योग ग्रेड उपज",
      tipHi: "फ्राई करने पर रंग अच्छा — कॉन्ट्रैक्ट फार्मिंग के लिए चुनें।",
    },
  ],
  bajra: [
    {
      name: "पायनियर 86M90 / 86M84",
      trait: "भारी लंबे सिट्टे, मोटा दाना; डाउनी मिल्ड्यू (जोगिया) प्रतिरोधी",
      season: "खरीफ",
      states: ["Rajasthan","Haryana","Uttar Pradesh","Gujarat"],
      source: "private",
      marketNote: "सिंचित व अच्छी बारिश वाले क्षेत्र",
      regionHi: "राजस्थान, हरियाणा, यू.पी., गुजरात — सिंचित/अच्छी बारिश",
      yieldHi: "12–15 कुंटल/एकड़",
      tipHi: "अर्गट (चिपकिया पदार्थ) दिखते ही तुरंत फफूंदनाशक स्प्रे — वरना दाने नहीं बनेंगे।",
    },
    {
      name: "HHB 67 संशोधित",
      trait: "सबसे कम अवधि 60–65 दिन; सूखा में भी दाना पक जाता है",
      season: "खरीफ",
      states: ["Rajasthan","Haryana","Gujarat"],
      source: "govt",
      marketNote: "सूखा/कम बारिश का वरदान",
      durationDays: { min: 60, max: 65 },
      regionHi: "अत्यधिक सूखा व कम बारिश वाले क्षेत्र",
      yieldHi: "8–10 कुंटल/एकड़",
      tipHi: "कम बारिश में भी दाना पूरा पकता है — ड्रायलैंड के लिए बेस्ट।",
    },
    {
      name: "बायो 70",
      trait: "द्वैत उद्देश्य — हरा चारा + मोटा दाना; लंबे पौधे",
      season: "खरीफ",
      states: ["Rajasthan","Haryana","Gujarat","Madhya Pradesh"],
      source: "private",
      marketNote: "चारा + दाना दोनों",
      regionHi: "हरा चारा और दाना दोनों के लिए",
      yieldHi: "अच्छा चारा + दाना",
      tipHi: "पशुपालन वाले किसानों के लिए ड्यूल पर्पस विकल्प।",
    },
  ],
  onion: [
    {
      name: "एग्रिफाउंड डार्क रेड",
      trait: "गहरा लाल, मध्यम गोल; बरसात में कंद नहीं सड़ते",
      season: "खरीफ",
      states: ["Maharashtra","Karnataka","Madhya Pradesh","Gujarat"],
      source: "govt",
      marketNote: "खरीफ प्याज की सबसे उपयुक्त किस्म",
      durationDays: { min: 95, max: 110 },
      regionHi: "खरीफ (बरसात) मौसम",
      yieldHi: "100–120 कुंटल/एकड़",
      tipHi: "खरीफ प्याज जलभराव नहीं सहती — हमेशा उठी क्यारी (रेज्ड बेड) पर रोपाई करें।",
    },
    {
      name: "भीमा शक्ति / एन-53",
      trait: "लंबी स्टोरेज — 5–6 महीने खराब नहीं होती",
      season: "रबी / लेट खरीफ",
      states: ["Maharashtra","Madhya Pradesh","Karnataka","Gujarat"],
      source: "govt",
      marketNote: "भंडारण व लेट मौसम की पसंद",
      durationDays: { min: 120, max: 130 },
      regionHi: "रबी व लेट-खरीफ",
      yieldHi: "120–140 कुंटल/एकड़",
      tipHi: "लंबे स्टोरेज के लिए खुदाई से 15 दिन पहले सिंचाई बंद करें — कंद सूख जाएँ।",
    },
    {
      name: "भीमा शुभ्रा",
      trait: "शुद्ध सफेद; पत्ती धब्बा व थ्रिप्स सहन; डीहाइड्रेशन/पाउडर",
      season: "रबी",
      states: ["Maharashtra","Gujarat","Madhya Pradesh"],
      source: "govt",
      marketNote: "सफेद प्याज व प्रोसेसिंग मार्केट",
      regionHi: "सफेद प्याज व प्रोसेसिंग",
      yieldHi: "अच्छी प्रोसेसिंग उपज",
      tipHi: "पाउडर/डीहाइड्रेशन इंडस्ट्री कॉन्ट्रैक्ट के लिए चुनें।",
    },
  ],
  cotton: [
    {
      name: "रासी 654 / 773 BG-II",
      trait: "Bt में सबसे भरोसेमंद; बड़े टिंडे; रसचूसक कीट सहिष्णु",
      season: "खरीफ",
      states: ["Maharashtra","Gujarat","Telangana","Madhya Pradesh"],
      source: "private",
      marketNote: "मध्य व दक्षिण भारत की टॉप Bt",
      regionHi: "मध्य व दक्षिण भारत",
      yieldHi: "10–12 कुंटल/एकड़",
      tipHi: "गुलाबी सुंडी पर Bt असर कम हो रहा है — खेत में फिरोमोन ट्रैप लगाना जरूरी।",
    },
    {
      name: "बनी BG-II (तुलसी)",
      trait: "उत्कृष्ट रेशा लंबाई व मजबूती — अच्छा भाव; तुड़ाई आसान",
      season: "खरीफ",
      states: ["Maharashtra","Gujarat","Andhra Pradesh","Telangana"],
      source: "private",
      marketNote: "फाइबर क्वालिटी प्रीमियम",
      regionHi: "सिंचित व हल्की-मध्यम भूमि",
      yieldHi: "12–14 कुंटल/एकड़",
      tipHi: "मैग्नीशियम कमी से पत्ते लाल होकर झड़ते हैं — MgSO₄ स्प्रे जरूर करें।",
    },
    {
      name: "सूरज (नॉन-Bt / HDPS)",
      trait: "सीधा पौधा; सघन बुवाई 60×15 सेमी; 140–150 दिन में खेत खाली",
      season: "खरीफ",
      states: ["Maharashtra","Telangana","Andhra Pradesh","Madhya Pradesh"],
      source: "govt",
      marketNote: "वर्षा आधारित सघन प्रणाली (HDPS)",
      durationDays: { min: 140, max: 150 },
      regionHi: "वर्षा आधारित + हाई डेंसिटी प्लांटिंग",
      yieldHi: "सघन बुवाई में अच्छी उपज",
      tipHi: "कम जगह में ज्यादा पौधे — HDPS अपनाते समय दूरी का ध्यान रखें।",
    },
  ],
  moong: [
    {
      name: "आईपीएम 02-3 (मेहा)",
      trait: "YMV 100% प्रतिरोधी; एक साथ पकना — एक बार में कटाई",
      season: "खरीफ / जायद",
      states: ["Uttar Pradesh","Madhya Pradesh","Rajasthan","Haryana","Bihar"],
      source: "govt",
      marketNote: "ऑल इंडिया — खरीफ व जायद",
      durationDays: { min: 60, max: 65 },
      regionHi: "खरीफ व जायद — पूरे भारत",
      yieldHi: "5–6 कुंटल/एकड़",
      tipHi: "YMV फैलाने वाली सफेद मक्खी का शुरू में ही नियंत्रण — वरना पूरी फसल पीली।",
    },
    {
      name: "सम्राट / PDM 139",
      trait: "अत्यंत अगेती 55–60 दिन; गर्मी में कम सिंचाई",
      season: "जायद",
      states: ["Punjab","Haryana","Uttar Pradesh","Rajasthan"],
      source: "govt",
      marketNote: "गेहूं कटाई के बाद जायद बुवाई",
      durationDays: { min: 55, max: 60 },
      regionHi: "जायद — गेहूं के बाद अगेती बुवाई",
      yieldHi: "4–5 कुंटल/एकड़",
      tipHi: "गर्मी में सिंचाई हल्की रखें — ज्यादा पानी से पत्ते ज्यादा, फूल कम।",
    },
    {
      name: "पूसा विशाल",
      trait: "बड़ा चमकदार हरा दाना — सब्जी व दाल दोनों माँग",
      season: "खरीफ / जायद",
      states: ["Uttar Pradesh","Madhya Pradesh","Haryana","Bihar"],
      source: "govt",
      marketNote: "सिंचित उत्तर-मध्य भारत",
      regionHi: "सिंचित क्षेत्र — उत्तर व मध्य भारत",
      yieldHi: "अच्छी मंडी माँग",
      tipHi: "बड़े दाने — सब्जी मंडी में अच्छा भाव।",
    },
  ],
  pulses: [
    {
      name: "यूपीएएस 120",
      trait: "अत्यंत अगेती 120–130 दिन — नवंबर तक खेत खाली, गेहूं समय पर",
      season: "खरीफ",
      states: ["Uttar Pradesh","Haryana","Punjab","Bihar"],
      source: "govt",
      marketNote: "गेहूं चक्र अपनाने वाले किसानों के लिए",
      durationDays: { min: 120, max: 130 },
      regionHi: "उत्तर-पश्चिम — गेहूं चक्र",
      yieldHi: "6–7 कुंटल/एकड़",
      tipHi: "फली छेदक फूल आते समय हमला करता है — नीम तेल (10000 PPM) प्रिवेंटिव स्प्रे लें।",
    },
    {
      name: "आशा / BDN 2",
      trait: "उकठा व बांझपन मोज़ेक पूर्ण प्रतिरोधी; गहरी जड़ें — सूखे में फलियाँ नहीं सूखतीं",
      season: "खरीफ",
      states: ["Maharashtra","Madhya Pradesh","Karnataka","Gujarat"],
      source: "govt",
      marketNote: "सूखा/वर्षा आधारित क्षेत्रों की मुख्य",
      durationDays: { min: 160, max: 180 },
      regionHi: "सूखा व बारिश आधारित — महाराष्ट्र, म.प्र., कर्नाटक",
      yieldHi: "8–10 कुंटल/एकड़",
      tipHi: "शुरुआती 45–50 दिन खेत खरपतवार मुक्त रखें — अरहर शुरू में धीरे बढ़ती है।",
    },
    {
      name: "पूसा 992",
      trait: "झाड़ीदार; गुच्छों में फलियाँ; ऊँची उपज क्षमता",
      season: "खरीफ",
      states: ["Uttar Pradesh","Madhya Pradesh","Haryana","Rajasthan"],
      source: "govt",
      marketNote: "सिंचित व अर्ध-सिंचित",
      regionHi: "सिंचित व अर्ध-सिंचित क्षेत्र",
      yieldHi: "8–10 कुंटल/एकड़",
      tipHi: "गुच्छों में फलियाँ — कटाई सुविधाजनक।",
    },
  ],
  chana: [
    {
      name: "जाकी 9218",
      trait: "किसान स्तर पर सबसे लोकप्रिय; बड़ा सुनहरा दाना; फ्यूजेरियम उकठा प्रतिरोधी",
      season: "रबी",
      states: ["Maharashtra","Madhya Pradesh","Andhra Pradesh","Karnataka"],
      source: "govt",
      marketNote: "मध्य व दक्षिण भारत की टॉप किस्म",
      durationDays: { min: 105, max: 110 },
      regionHi: "मध्य व दक्षिण भारत",
      yieldHi: "8–10 कुंटल/एकड़",
      tipHi: "बुवाई के 30–35 दिन पर निपिंग (ऊपर की शिखा तोड़ना) — साइड शाखाएँ व फलियाँ ज्यादा।",
    },
    {
      name: "GNG 1581 (गणगौर)",
      trait: "सिंचित व सीमित सिंचाई दोनों; पाला व उकठा सहन",
      season: "रबी",
      states: ["Rajasthan","Haryana","Punjab","Uttar Pradesh"],
      source: "govt",
      marketNote: "उत्तर भारत की भरोसेमंद किस्म",
      durationDays: { min: 140, max: 145 },
      regionHi: "उत्तर भारत — राजस्थान, हरियाणा, पंजाब, पश्चिमी यू.पी.",
      yieldHi: "10–12 कुंटल/एकड़",
      tipHi: "फूल आने पर सिंचाई न करें — पानी लगते ही फूल झड़ जाते हैं।",
    },
    {
      name: "जेजी 11",
      trait: "असिंचित/ड्रायलैंड — कम नमी में भी जड़ विकास अच्छा",
      season: "रबी",
      states: ["Madhya Pradesh","Maharashtra","Rajasthan"],
      source: "govt",
      marketNote: "वर्षा आधारित चना की मुख्य किस्म",
      regionHi: "असिंचित / बारिश आधारित क्षेत्र",
      yieldHi: "कम पानी में स्थिर उपज",
      tipHi: "ड्रायलैंड चना के लिए सुरक्षित विकल्प।",
    },
  ],
  masoor: [
    {
      name: "एल 4076 / पूसा वैभव",
      trait: "बड़ा दाना; गेरुआ व उकठा दोनों प्रतिरोधी",
      season: "रबी",
      states: ["Uttar Pradesh","Bihar","West Bengal","Madhya Pradesh"],
      source: "govt",
      marketNote: "उत्तर व पूर्वी भारत की बोल्ड सीडेड",
      durationDays: { min: 120, max: 125 },
      regionHi: "उत्तर व पूर्वी भारत",
      yieldHi: "6–8 कुंटल/एकड़",
      tipHi: "उकठा सबसे बड़ी बीमारी — बुवाई से पहले बीज को ट्राइकोडर्मा से उपचारित करें।",
    },
    {
      name: "आईपीएल 81 / शेरी",
      trait: "देर बुवाई में भी उपज नहीं घटती — धान कटाई के बाद सुरक्षित",
      season: "रबी",
      states: ["Uttar Pradesh","Bihar","Madhya Pradesh","West Bengal"],
      source: "govt",
      marketNote: "लेट सोइंग क्षेत्रों के लिए",
      durationDays: { min: 110, max: 115 },
      regionHi: "देर से बुवाई वाले क्षेत्र",
      yieldHi: "लेट सोइंग में स्थिर उपज",
      tipHi: "धान कटाई के बाद देर बुवाई पर भी उत्पादन बना रहता है।",
    },
  ],
  urad: [
    {
      name: "पंत उड़द 31 (PU 31)",
      trait: "YMV व चूर्णी फफूंद से सुरक्षित; मोटा काला चमकदार दाना",
      season: "खरीफ / जायद",
      states: ["Uttar Pradesh","Uttarakhand","Madhya Pradesh","Bihar","Rajasthan"],
      source: "govt",
      marketNote: "ऑल इंडिया — खरीफ व जायद",
      durationDays: { min: 70, max: 75 },
      regionHi: "खरीफ व जायद — पूरे भारत",
      yieldHi: "5–6 कुंटल/एकड़",
      tipHi: "उड़द जलभराव नहीं सहती — एक बारिश का पानी रुका तो फसल पीली; जल निकासी बेस्ट रखें।",
    },
    {
      name: "शेखर 2 / IPU 2-43",
      trait: "एक साथ पकना; फलियाँ ऊपर — कटाई आसान",
      season: "खरीफ",
      states: ["Uttar Pradesh","Madhya Pradesh","Bihar"],
      source: "govt",
      marketNote: "मध्य व उत्तर मैदान",
      regionHi: "मध्य व उत्तर भारत के मैदानी क्षेत्र",
      yieldHi: "अच्छी औसत उपज",
      tipHi: "फलियाँ ऊपर रहती हैं — मशीन/हाथ कटाई आसान।",
    },
  ],
  mustard: [
    {
      name: "पायनियर 45S46",
      trait: "हाइब्रिड नंबर 1; तेल 41–42%; मोटा वजनी दाना; lodging नहीं",
      season: "रबी",
      states: ["Rajasthan","Haryana","Uttar Pradesh","Madhya Pradesh"],
      source: "private",
      marketNote: "भारत की टॉप हाइब्रिड सरसों",
      durationDays: { min: 125, max: 130 },
      regionHi: "ऑल इंडिया सिंचित — राजस्थान, हरियाणा, यू.पी., म.प्र.",
      yieldHi: "10–12 कुंटल/एकड़",
      tipHi: "फूल आने पर अक्सर माहू (चेपा) — ठंड बढ़ने पर इमिडाक्लोप्रिड या थायमेथोक्साम स्प्रे रेडी रखें।",
    },
    {
      name: "पूसा सरसों 30 / LES 39",
      trait: "लो एरूसिक एसिड (<2%) — दिल की सेहत के लिए उत्तम तेल",
      season: "रबी",
      states: ["Rajasthan","Haryana","Uttar Pradesh","Madhya Pradesh","Bihar"],
      source: "govt",
      marketNote: "हेल्थ ऑयल उत्पादकों की पसंद",
      regionHi: "स्वास्थ्यवर्धक तेल व सामान्य क्षेत्र",
      yieldHi: "8–10 कुंटल/एकड़",
      tipHi: "सल्फर (बेंटोनाइट) 10–15 किग्रा/एकड़ डालें — तेल मात्रा व दाने की चमक बढ़ती है।",
    },
    {
      name: "RH 749 / NRCHB 101",
      trait: "लंबे पौधे, ज्यादा शाखाएँ; क्षारीय/खारे पानी में भी",
      season: "रबी",
      states: ["Haryana","Rajasthan","Uttar Pradesh"],
      source: "govt",
      marketNote: "सिंचित व खारे पानी वाले क्षेत्र",
      durationDays: { min: 135, max: 140 },
      regionHi: "सिंचित व क्षारीय/खारे पानी वाले क्षेत्र",
      yieldHi: "10–12 कुंटल/एकड़",
      tipHi: "ऊँची शाखाएँ — अच्छी प्रबंधन से ऊँची उपज।",
    },
  ],
  bhindi: [
    {
      name: "महिको राधिका",
      trait: "YVMV व ELCV अत्यधिक प्रतिरोधी; गहरा हरा 5-धारी नरम फल",
      season: "खरीफ / जायद",
      states: ["Maharashtra","Gujarat","Madhya Pradesh","Uttar Pradesh","Karnataka","Andhra Pradesh"],
      source: "private",
      marketNote: "ऑल इंडिया हाइब्रिड — खरीफ व जायद",
      regionHi: "ऑल इंडिया — खरीफ व जायद",
      yieldHi: "60–80 कुंटल/एकड़",
      tipHi: "बीज दर 1.5–2 किग्रा/एकड़ — बहुत सघन बुवाई से तुड़ाई में लेबर दिक्कत। पहली तुड़ाई 45–50 दिन।",
    },
    {
      name: "सिंजेंटा 1021",
      trait: "उत्कृष्ट शेल्फ लाइफ; ज्यादा शाखाएँ — 3–4 महीने तुड़ाई",
      season: "खरीफ / जायद",
      states: ["Maharashtra","Gujarat","Madhya Pradesh","Karnataka","Andhra Pradesh"],
      source: "private",
      marketNote: "लंबी दूरी मंडी व लंबी तुड़ाई अवधि",
      regionHi: "सिंचित क्षेत्र — लंबी दूरी बाजार",
      yieldHi: "70–85 कुंटल/एकड़",
      tipHi: "मंडी में लंबे समय अच्छे रेट के लिए — हार्वेस्टिंग विंडो लंबी चलती है।",
    },
    {
      name: "काशी क्रांति / अर्का अनामिका",
      trait: "OP — बीज खुद बचा सकते हैं; रोग प्रतिरोध अच्छा; कम लागत",
      season: "खरीफ / गर्मी",
      states: ["Uttar Pradesh","Bihar","Madhya Pradesh","Karnataka","Maharashtra","Andhra Pradesh"],
      source: "govt",
      marketNote: "कम बजट किसानों की भरोसेमंद",
      regionHi: "ओपन-पॉलीनेटेड — कम लागत खेती",
      yieldHi: "50–60 कुंटल/एकड़",
      tipHi: "OP है — बीज खुद तैयार करके अगले साल रख सकते हैं, बीज खर्च बचता है।",
    },
  ],
  ginger: [
    {
      name: "वरदा (IISR)",
      trait: "सबसे लोकप्रिय; कम रेशा — प्रोसेसिंग व सोंठ के लिए उत्तम",
      season: "खरीफ",
      states: ["Kerala","Karnataka","Madhya Pradesh","Odisha","Assam"],
      source: "govt",
      marketNote: "सोंठ रिकवरी 20–22% — प्रोसेसिंग में ज्यादा मुनाफा",
      regionHi: "केरल, कर्नाटक, पूर्वोत्तर व मध्य भारत",
      yieldHi: "9–11 टन/एकड़ (ताजा)",
      tipHi: "सूखी सोंठ रिकवरी 20–22% — प्रोसेसिंग इंडस्ट्री में सबसे ज्यादा मुनाफे वाली।",
    },
    {
      name: "महिमा",
      trait: "कंद सड़न व जड़-गाँठ निमाटोड सहन; बड़े वजनदार कंद",
      season: "खरीफ",
      states: ["Kerala","Karnataka","Odisha","Madhya Pradesh"],
      source: "govt",
      marketNote: "रोग इतिहास वाले खेतों के लिए सुरक्षित",
      regionHi: "कंद सड़न व निमाटोड प्रभावित क्षेत्र",
      yieldHi: "9–10 टन/एकड़",
      tipHi: "जिन खेतों में निमाटोड/राइजोम रॉट पुराना इतिहास हो — सबसे सुरक्षित किस्म।",
    },
    {
      name: "रियो-डी-जिनेरो",
      trait: "बहुत बड़े रसदार कंद — ताजा हरी अदरक बाजार",
      season: "खरीफ",
      states: ["Kerala","Karnataka","Himachal Pradesh","West Bengal"],
      source: "govt",
      marketNote: "ताजा सब्जी मंडी में सबसे ज्यादा बिकती",
      regionHi: "ताजा हरी अदरक बेचने के लिए",
      yieldHi: "12–15 टन/एकड़",
      tipHi: "रेशा ज्यादा — सोंठ नहीं बना सकते; सिर्फ हरी/ताजा अदरक के रूप में बेचें।",
    },
  ],
  garlic: [
    {
      name: "जी-282 / यमुना सफेद-3",
      trait: "बड़ी सफेद कलियाँ — एक्सपोर्ट क्वालिटी",
      season: "रबी",
      states: ["Madhya Pradesh","Rajasthan","Gujarat","Haryana","Uttar Pradesh"],
      source: "govt",
      marketNote: "निर्यात के लिए सबसे पसंद",
      regionHi: "ऑल इंडिया — खासकर म.प्र., राजस्थान, गुजरात",
      yieldHi: "70–80 कुंटल/एकड़",
      tipHi: "एक्सपोर्ट के लिए कंद साइज 50mm+ चाहिए — सही पोषण पर आसानी से बन जाता है।",
    },
    {
      name: "जी-50 / यमुना सफेद-1",
      trait: "तीखापन तेज; स्टोरेज 6–8 महीने — वजन कम नहीं होता",
      season: "रबी",
      states: ["Madhya Pradesh","Uttar Pradesh","Haryana","Rajasthan","Punjab"],
      source: "govt",
      marketNote: "लंबे भंडारण वाली किस्म",
      regionHi: "मध्य व उत्तर भारत मैदान",
      yieldHi: "60–70 कुंटल/एकड़",
      tipHi: "6–8 महीने स्टोर पर भी कलियों का वजन कम नहीं होता।",
    },
    {
      name: "भीमा पर्पल",
      trait: "बैंगनी छिलका; 120–130 दिन; खरीफ व रबी दोनों",
      season: "खरीफ / रबी",
      states: ["Maharashtra","Madhya Pradesh","Gujarat","Rajasthan"],
      source: "govt",
      marketNote: "बैंगनी/गुलाबी लहसुन माँग वाले क्षेत्र",
      durationDays: { min: 120, max: 130 },
      regionHi: "बैंगनी लहसुन माँग वाले क्षेत्र",
      yieldHi: "60–65 कुंटल/एकड़",
      tipHi: "खरीफ व रबी दोनों सीजन में उगाई जा सकने वाली अनुकूल किस्म।",
    },
  ],
  mango: [
    {
      name: "आम्रपाली",
      trait: "बौनी HDP — 2.5×2.5 मी पर ~640 पौधे/एकड़; नियमित फलन हर साल",
      season: "गर्मी कटाई",
      states: ["Uttar Pradesh","Bihar","Maharashtra","Gujarat","Karnataka","Andhra Pradesh"],
      source: "govt",
      marketNote: "सघन बागवानी के लिए ऑल इंडिया",
      regionHi: "हाई डेंसिटी प्लांटिंग — ऑल इंडिया",
      yieldHi: "6–8 टन/एकड़ (सघन बागवानी में)",
      tipHi: "2.5×2.5 मी पर हर साल कटाई-छंटाई अनिवार्य — वरना फलन बहुत कम।",
    },
    {
      name: "दशहरी / लंगड़ा",
      trait: "उत्तर भारत की मिठास व सुगंध की पसंदीदा किस्में",
      season: "गर्मी कटाई",
      states: ["Uttar Pradesh","Bihar","Punjab","Haryana"],
      source: "govt",
      marketNote: "उत्तर भारत टेबल आम",
      regionHi: "उत्तर भारत — यू.पी., बिहार, पंजाब, हरियाणा",
      yieldHi: "4–5 टन/एकड़ (पारंपरिक दूरी)",
      tipHi: "एकांतर फलन समस्या — कंट्रोल के लिए पैक्लोबुट्राजोल का इस्तेमाल जरूरी।",
    },
    {
      name: "अल्फांसो / हापुस",
      trait: "विश्व प्रसिद्ध एक्सपोर्ट — अंतरराष्ट्रीय बाजार में सबसे ज्यादा दाम",
      season: "गर्मी कटाई",
      states: ["Maharashtra","Gujarat","Karnataka"],
      source: "govt",
      marketNote: "कोंकण एक्सपोर्ट वैरायटी",
      regionHi: "पश्चिमी भारत — महाराष्ट्र कोंकण, गुजरात",
      yieldHi: "3–4 टन/एकड़",
      tipHi: "स्पंजी टिश्यू समस्या — फलों के विकास समय कैल्शियम स्प्रे बहुत जरूरी।",
    },
  ],
  banana: [
    {
      name: "ग्रैंड नैन G-9",
      trait: "टिश्यू कल्चर; घोंद 30–45 किग्रा; मध्यम ऊँचाई — हवा में कम गिरता",
      season: "साल भर",
      states: ["Maharashtra","Gujarat","Andhra Pradesh","Tamil Nadu","Karnataka","Madhya Pradesh"],
      source: "private",
      marketNote: "भारत में ~90% व्यावसायिक खेती",
      regionHi: "ऑल इंडिया व्यावसायिक खेती",
      yieldHi: "35–40 टन/एकड़",
      tipHi: "इतनी उपज के लिए फर्टिगेशन (ड्रिप) अनिवार्य; भारी घोंद के लिए बांस सहारा (प्रॉपिंग) दें।",
    },
    {
      name: "रोबस्टा / हरिछाल",
      trait: "पकने पर छिलका हल्का हरा-पीला; मीठा गुदेदार फल",
      season: "साल भर",
      states: ["Karnataka","Tamil Nadu","Kerala","Madhya Pradesh"],
      source: "govt",
      marketNote: "दक्षिण व मध्य भारत",
      regionHi: "दक्षिण व मध्य भारत",
      yieldHi: "30–35 टन/एकड़",
      tipHi: "सिगाटोका लीफ स्पॉट के प्रति संवेदनशील — फफूंदनाशक स्प्रे शेड्यूल मजबूत रखें।",
    },
    {
      name: "नेन्द्रन",
      trait: "चिप्स व प्रोसेसिंग के लिए सर्वश्रेष्ठ; छोटा फसल चक्र 9–10 महीने",
      season: "साल भर",
      states: ["Kerala","Tamil Nadu"],
      source: "govt",
      marketNote: "चिप्स कंपनियों की कॉन्ट्रैक्ट किस्म",
      regionHi: "केरल व तमिलनाडु — चिप्स उद्योग",
      yieldHi: "12–15 टन/एकड़",
      tipHi: "चिप्स बनाने वाली कंपनियों के साथ कॉन्ट्रैक्ट फार्मिंग के लिए सबसे अच्छी।",
    },
  ],
  grapes: [
    {
      name: "थॉमसन सीडलेस",
      trait: "बीज-रहित; किशमिश व ताजा दोनों; भारत उत्पादन का 80%+",
      season: "सर्दी / वसंत",
      states: ["Maharashtra","Karnataka","Andhra Pradesh"],
      source: "govt",
      marketNote: "नाशिक-सांगली एक्सपोर्ट क्लस्टर",
      regionHi: "महाराष्ट्र (नाशिक, सांगली), कर्नाटक, आंध्र",
      yieldHi: "10–12 टन/एकड़",
      tipHi: "बेरी साइज बढ़ाने के लिए GA3 डिपिंग/स्प्रे के बिना व्यावसायिक खेती अधूरी।",
    },
    {
      name: "माणिक चमन (2A क्लोन)",
      trait: "थॉमसन का सुधरा रूप; कम फटना; लंबी दूरी परिवहन मजबूत",
      season: "सर्दी / वसंत",
      states: ["Maharashtra","Karnataka"],
      source: "govt",
      marketNote: "बेरी ड्रॉप व पानी कमी क्षेत्रों के लिए",
      regionHi: "बेरी गिरने व पानी कमी वाले क्षेत्र",
      yieldHi: "12–14 टन/एकड़",
      tipHi: "अत्यधिक नमी/बेमौसम बारिश में बेरी क्रैकिंग काफी कम।",
    },
    {
      name: "फ्लेम सीडलेस",
      trait: "लाल-बैंगनी बीज-रहित; अत्यधिक मीठा (हाई TSS)",
      season: "सर्दी",
      states: ["Maharashtra","Karnataka","Andhra Pradesh"],
      source: "govt",
      marketNote: "फैंसी रेड ग्रेप्स मार्केट",
      regionHi: "लाल अंगूर बाजार",
      yieldHi: "8–10 टन/एकड़",
      tipHi: "एकसमान लाल रंग के लिए इथरेल (एथेफॉन) छिड़काव करना पड़ता है।",
    },
  ],
  papaya: [
    {
      name: "रेड लेडी 786 / ताइवान 786",
      trait: "उभयलिंगी — हर पौधे पर फल; गहरा लाल मीठा गुदा (TSS 13–14%); कड़ा फल",
      season: "साल भर",
      states: ["Maharashtra","Gujarat","Andhra Pradesh","Madhya Pradesh","Karnataka","Uttar Pradesh"],
      source: "private",
      marketNote: "व्यावसायिक खेती की सबसे लोकप्रिय",
      regionHi: "ऑल इंडिया व्यावसायिक",
      yieldHi: "25–30 टन/एकड़ (~40–50 किग्रा/पौधा)",
      tipHi: "जड़ें जलभराव नहीं सहतीं (कॉलर रॉट) — हमेशा उठी क्यारियों पर ही लगाएँ।",
    },
    {
      name: "पूसा नन्हा",
      trait: "अल्ट्रा बौना 1–1.5 मी; 30 सेमी से फल; गमले/किचन गार्डन",
      season: "साल भर",
      states: ["Delhi","Uttar Pradesh","Haryana","Madhya Pradesh","Bihar"],
      source: "govt",
      marketNote: "गृह वाटिका व सघन खेती",
      regionHi: "किचन गार्डन व सघन खेती",
      yieldHi: "15–20 टन/एकड़",
      tipHi: "1.25×1.25 मी पर सघन लगाया जा सकता है — छत/किचन गार्डन के लिए बेस्ट।",
    },
    {
      name: "अर्का प्रभात (IIHR)",
      trait: "रिंग स्पॉट वायरस सहन; चमकदार गुलाबी-लाल गुदा",
      season: "साल भर",
      states: ["Karnataka","Andhra Pradesh","Tamil Nadu","Maharashtra","Madhya Pradesh"],
      source: "govt",
      marketNote: "दक्षिण व मध्य भारत",
      regionHi: "दक्षिण व मध्य भारत",
      yieldHi: "25–30 टन/एकड़",
      tipHi: "PRSV सहनशील है, पर वेक्टर (सफेद मक्खी/माहू) नियंत्रण लगातार करते रहें।",
    },
  ],
  capsicum: [
    {
      name: "इंदिरा",
      trait: "ब्लॉकी हरा हाइब्रिड — शहरी मंडी प्रीमियम",
      season: "रबी / संरक्षित",
      states: ["Maharashtra","Karnataka","Haryana"],
      source: "private",
      marketNote: "शहरी wholesale प्रीमियम",
      regionHi: "पॉलीहाउस व रबी",
      yieldHi: "अच्छी संरक्षित उपज",
      tipHi: "नमी नियंत्रण व फंगल स्प्रे शेड्यूल नियमित रखें।",
    },
  ],
};

const FALLBACK: MarketVarietyRec[] = [
  {
    name: "प्रमाणित स्थानीय HYV",
    trait: "राज्य बीज निगम / कृषि विभाग की सूची से चुनें",
    season: "मुख्य मौसम",
    states: [],
    source: "govt",
    marketNote: "नजदीकी मंडी में पूछें — कौन-सी किस्म का भाव सबसे अच्छा मिलता है",
    tipHi: "अपने जिले की अनुशंसित सूची कृषि अधिकारी से जरूर मिला लें।",
  },
];

function normalizeState(state?: string): string {
  return (state ?? "").trim().toLowerCase();
}

/** Per-crop varieties; prefer those matching farmer state for market tip ordering */
export function getVarietiesForCrop(cropSlug: string, state?: string): MarketVarietyRec[] {
  const slug = cropSlug.trim().toLowerCase();
  const aliased =
    slug === "groundnut" || slug === "mungfali"
      ? "moongfali"
      : slug === "arhar" || slug === "tur" || slug === "pigeonpea" || slug === "tuar"
        ? "pulses"
        : slug === "rice" || slug === "dhaan"
          ? "paddy"
          : slug === "okra" || slug === "ladyfinger"
            ? "bhindi"
            : slug === "baingan" || slug === "eggplant"
              ? "brinjal"
              : slug === "pyaz"
                ? "onion"
                : slug === "aloo"
                  ? "potato"
                  : slug === "tamatar"
                    ? "tomato"
                    : slug === "mirch"
                      ? "chilli"
                      : slug === "phoolgobhi"
                        ? "cauliflower"
                        : slug === "kheera"
                          ? "cucumber"
                          : slug === "ganna"
                            ? "sugarcane"
                            : slug === "kapas"
                              ? "cotton"
                              : slug === "sarso"
                                ? "mustard"
                                : slug === "gehu"
                                  ? "wheat"
                                  : slug === "makka"
                                    ? "maize"
                                    : slug === "papita"
                                      ? "papaya"
                                      : slug === "angur"
                                        ? "grapes"
                                        : slug === "kela"
                                          ? "banana"
                                          : slug === "aam"
                                            ? "mango"
                                            : slug;

  const list = VARIETIES_BY_CROP[aliased] ?? FALLBACK;
  const s = normalizeState(state);
  if (!s) return list;
  const matched = list.filter((v) => v.states.some((st) => st.toLowerCase() === s));
  const rest = list.filter((v) => !v.states.some((st) => st.toLowerCase() === s));
  return matched.length ? [...matched, ...rest] : list;
}
