import type { CropFertilizerMixinGuide } from "./fertilizerMixinFieldGuide";

export const PART2_GUIDES: Record<string, CropFertilizerMixinGuide> = {
  chana: {
    cropNameHi: "चना",
    englishName: "Chickpea",
    categoryHi: "दलहन",
    totalNutrientsHi: [
      "N 8–10 kg/acre",
      "P₂O₅ 20–24 kg/acre",
      "K₂O 12 kg/acre",
      "S 8 kg/acre",
    ],
    totalFertilizerHi: [
      "SSP 100 kg/acre (विकल्प)",
      "DAP 35–40 kg/acre (विकल्प)",
      "MOP 15 kg/acre",
      "S 90% 5 kg/acre",
    ],
    globalWarningsHi: [
      "SOURCE DATA — VERIFY BEFORE OPERATIONAL USE",
      "दलहन पर खड़ी फसल में यूरिया प्रसार (broadcast) मत करो — DALHAN UREA ALERT",
      "PEAK BLOOM स्प्रे समय — हल्की सिंचाई/शाम के बाद, पंखुड़ी झड़ने से बचो",
      "स्रोत: बेसल में SSP को DAP से अधिक पसंद — यह स्रोत framing है, गारंटी नहीं",
    ],
    stages: [
      {
        stageNumber: 0,
        stageNameHi: "बीज उपचार",
        timingHi: "बुवाई से पहले",
        activityHi:
          "क्रम: fungicide → insecticide → Rhizobium+PSB; छाया में सुखाओ; 6 घंटे के अंदर बोओ",
        seedTreatment: [
          {
            kind: "fungicide",
            technical: "Carbendazim + Mancozeb",
            doseHi: "2 g/kg बीज",
            brands: ["Saaf"],
            targetHi: "बीजजनित रोग",
          },
          {
            kind: "insecticide",
            technical: "Thiamethoxam",
            formulation: "30% FS",
            doseHi: "2 ml/kg बीज",
            targetHi: "दीमक",
          },
          {
            kind: "biofertilizer",
            technical: "Rhizobium + PSB",
            doseHi: "5 g/kg बीज",
          },
        ],
        mixingHi:
          "क्रम F → I → R; अलग-अलग मिलाओ, छाया में सुखाकर 6 घंटे के अंदर बुवाई",
        mixingStatus: "seed_only",
        fertilizers: [],
        pestProtection: [],
        diseaseProtection: [],
        rootBio: [],
        pgr: [],
        foliar: [],
      },
      {
        stageNumber: 1,
        stageNameHi: "बेसल / बुवाई",
        timingHi: "बुवाई के समय",
        fertilizers: [
          {
            kind: "fertilizer",
            technical: "SSP",
            doseHi: "100 kg/acre",
            options: [
              {
                kind: "fertilizer",
                technical: "DAP",
                doseHi: "35 kg/acre",
              },
            ],
          },
          {
            kind: "fertilizer",
            technical: "MOP",
            doseHi: "15 kg/acre",
          },
          {
            kind: "fertilizer",
            technical: "Sulphur",
            formulation: "90%",
            doseHi: "5 kg/acre",
          },
          {
            kind: "humic",
            technical: "Humic Acid",
            formulation: "98% Powder",
            doseHi: "500 g/acre",
            options: [
              {
                kind: "humic",
                technical: "Humic Acid",
                formulation: "Granular",
                doseHi: "5 kg/acre",
              },
            ],
            sourceClaimHi: "स्रोत दावा: humic से जड़ें लगभग 2 फीट तक",
          },
        ],
        pestProtection: [
          {
            kind: "insecticide",
            technical: "Fipronil",
            formulation: "0.3% GR",
            doseHi: "8 kg/acre",
            targetHi: "दीमक / कटवर्म",
          },
        ],
        diseaseProtection: [],
        rootBio: [],
        pgr: [],
        seedTreatment: [],
        foliar: [],
        placementHi: "बीज से 2 inch नीचे की कुंडी/फरो में",
      },
      {
        stageNumber: 2,
        stageNameHi: "शाखा / वृद्धि",
        timingHi: "30–35 DAS",
        activityHi: "हल्की सिंचाई के बाद foliar",
        foliar: [
          {
            kind: "foliar",
            technical: "19:19:19",
            doseHi: "1 kg",
            waterHi: "150 L पानी में",
          },
          {
            kind: "biostimulant",
            technical: "Amino Acid Tonic",
            doseHi: "250 ml",
            waterHi: "150 L पानी में (19:19:19 के साथ)",
          },
        ],
        fertilizers: [],
        pestProtection: [],
        diseaseProtection: [],
        rootBio: [],
        pgr: [],
        seedTreatment: [],
        moistureHi: "हल्की सिंचाई के बाद छिड़काव",
      },
      {
        stageNumber: 3,
        stageNameHi: "फूल–फली",
        timingHi: "55–65 DAS",
        activityHi: "फूल टिकाव — मिट्टी में खाद नहीं; foliar only",
        foliar: [
          {
            kind: "foliar",
            technical: "0:52:34",
            doseHi: "1 kg",
            waterHi: "150 L पानी में",
          },
          {
            kind: "micronutrient",
            technical: "Boron",
            formulation: "20%",
            doseHi: "100 g",
            waterHi: "150 L पानी में",
          },
          {
            kind: "insecticide",
            technical: "Emamectin Benzoate",
            formulation: "5% SG",
            doseHi: "80 g",
            waterHi: "150 L पानी में",
          },
        ],
        dontHi: ["इस चरण में मिट्टी में कोई उर्वरक न डालें"],
        fertilizers: [],
        pestProtection: [],
        diseaseProtection: [],
        rootBio: [],
        pgr: [],
        seedTreatment: [],
      },
      {
        stageNumber: 4,
        stageNameHi: "दाना भराव",
        timingHi: "75–80 DAS",
        foliar: [
          {
            kind: "foliar",
            technical: "13:0:45",
            doseHi: "1 kg",
            waterHi: "150 L पानी में",
            purposeHi: "दाना वजन / चमक",
          },
        ],
        fertilizers: [],
        pestProtection: [],
        diseaseProtection: [],
        rootBio: [],
        pgr: [],
        seedTreatment: [],
      },
    ],
  },

  pulses: {
    cropNameHi: "अरहर / तूर",
    englishName: "Pigeon pea",
    categoryHi: "दलहन",
    totalFertilizerHi: [
      "DAP 40 kg/acre",
      "MOP 20 kg/acre",
      "S 90% 5 kg/acre",
      "Zinc sulphate 33% 5 kg/acre",
    ],
    globalWarningsHi: [
      "SOURCE DATA — VERIFY BEFORE OPERATIONAL USE",
      "PEAK BLOOM स्प्रे समय — हल्की सिंचाई/शाम के बाद, पंखुड़ी झड़ने से बचो",
    ],
    stages: [
      {
        stageNumber: 0,
        stageNameHi: "बीज उपचार",
        timingHi: "बुवाई से पहले",
        seedTreatment: [
          {
            kind: "fungicide",
            technical: "Trichoderma",
            doseHi: "5 g/kg बीज",
            targetHi: "विल्ट / root rot",
            sourceClaimHi: "स्रोत दावा: 100% सुरक्षा — SOURCE_CLAIM",
          },
          {
            kind: "insecticide",
            technical: "Thiamethoxam",
            formulation: "30% FS",
            doseHi: "2 ml/kg बीज",
          },
        ],
        mixingStatus: "seed_only",
        fertilizers: [],
        pestProtection: [],
        diseaseProtection: [],
        rootBio: [],
        pgr: [],
        foliar: [],
      },
      {
        stageNumber: 1,
        stageNameHi: "बेसल / बुवाई",
        timingHi: "बुवाई के समय",
        fertilizers: [
          {
            kind: "fertilizer",
            technical: "DAP",
            doseHi: "40 kg/acre",
          },
          {
            kind: "fertilizer",
            technical: "MOP",
            doseHi: "20 kg/acre",
          },
          {
            kind: "fertilizer",
            technical: "Sulphur",
            formulation: "90%",
            doseHi: "5 kg/acre",
          },
          {
            kind: "humic",
            technical: "Humic Acid",
            formulation: "Granular",
            doseHi: "5 kg/acre",
          },
        ],
        pestProtection: [
          {
            kind: "insecticide",
            technical: "Fipronil",
            formulation: "0.3% GR",
            doseHi: "8 kg/acre",
            targetHi: "white grub / दीमक",
          },
        ],
        diseaseProtection: [],
        rootBio: [],
        pgr: [],
        seedTreatment: [],
        foliar: [],
        placementHi: "फरो में बुवाई",
      },
      {
        stageNumber: 2,
        stageNameHi: "पहली निराई / earth up",
        timingHi: "35–40 DAS",
        activityHi: "पहली निराई पर कतार में earth up",
        fertilizers: [
          {
            kind: "biostimulant",
            technical: "Seaweed",
            formulation: "Granular",
            doseHi: "10 kg/acre",
            brands: ["Sagarika", "Biozyme"],
          },
        ],
        pestProtection: [],
        diseaseProtection: [],
        rootBio: [],
        pgr: [],
        seedTreatment: [],
        foliar: [],
      },
      {
        stageNumber: 3,
        stageNameHi: "PGR / foliar (शर्त)",
        timingHi: "65–75 DAS",
        activityHi: "अत्यधिक लंबी वृद्धि हो तभी PGR",
        pgr: [
          {
            kind: "pgr",
            technical: "Mepiquat Chloride",
            formulation: "5% AS",
            doseHi: "250 ml/acre",
            noteHi: "केवल जब पौधे अत्यधिक लंबे हों",
          },
        ],
        foliar: [
          {
            kind: "foliar",
            technical: "19:19:19",
            doseHi: "1 kg",
            waterHi: "150 L पानी में",
          },
        ],
        mixingStatus: "validation",
        fertilizers: [],
        pestProtection: [],
        diseaseProtection: [],
        rootBio: [],
        seedTreatment: [],
      },
      {
        stageNumber: 4,
        stageNameHi: "फूल–फली foliar",
        timingHi: "100–115 DAS",
        foliar: [
          {
            kind: "foliar",
            technical: "0:52:34",
            doseHi: "1 kg",
            waterHi: "150 L पानी में",
          },
          {
            kind: "micronutrient",
            technical: "Boron",
            formulation: "20%",
            doseHi: "150 g",
            waterHi: "150 L पानी में",
          },
        ],
        pgr: [
          {
            kind: "pgr",
            technical: "Alpha Naphthalene Acetic Acid",
            doseHi: "40 ml",
            waterHi: "150 L पानी में",
            brands: ["Planofix"],
            sourceClaimHi: "स्रोत दावा: फूल झड़ने पर नियंत्रण",
          },
        ],
        fertilizers: [],
        pestProtection: [],
        diseaseProtection: [],
        rootBio: [],
        seedTreatment: [],
      },
    ],
  },

  moong: {
    cropNameHi: "मूंग",
    englishName: "Green gram",
    categoryHi: "दलहन",
    principlesHi: ["फसल अवधि लगभग 60 दिन"],
    totalFertilizerHi: [
      "DAP 30 kg/acre",
      "MOP 15 kg/acre",
      "S 90% 3 kg/acre",
    ],
    globalWarningsHi: [
      "SOURCE DATA — VERIFY BEFORE OPERATIONAL USE",
      "दलहन पर खड़ी फसल में यूरिया प्रसार (broadcast) मत करो — DALHAN UREA ALERT",
      "PEAK BLOOM स्प्रे समय — हल्की सिंचाई/शाम के बाद, पंखुड़ी झड़ने से बचो",
    ],
    stages: [
      {
        stageNumber: 0,
        stageNameHi: "बीज उपचार",
        timingHi: "बुवाई से पहले",
        seedTreatment: [
          {
            kind: "fungicide",
            technical: "Carboxin + Thiram",
            doseHi: "2 g/kg बीज",
            brands: ["Vitavax Power"],
          },
          {
            kind: "insecticide",
            technical: "Imidacloprid",
            formulation: "600 FS",
            doseHi: "2 ml/kg बीज",
            targetHi: "whitefly / YMV",
            sourceClaimHi: "स्रोत: whitefly / YMV से बचाव का उल्लेख",
          },
        ],
        mixingStatus: "seed_only",
        fertilizers: [],
        pestProtection: [],
        diseaseProtection: [],
        rootBio: [],
        pgr: [],
        foliar: [],
      },
      {
        stageNumber: 1,
        stageNameHi: "बेसल / बुवाई",
        timingHi: "बुवाई के समय",
        fertilizers: [
          {
            kind: "fertilizer",
            technical: "DAP",
            doseHi: "30 kg/acre",
          },
          {
            kind: "fertilizer",
            technical: "MOP",
            doseHi: "15 kg/acre",
          },
          {
            kind: "fertilizer",
            technical: "Sulphur",
            formulation: "90%",
            doseHi: "3 kg/acre",
          },
          {
            kind: "humic",
            technical: "Humic Acid",
            formulation: "98%",
            doseHi: "500 g/acre",
          },
        ],
        placementHi: "फरो में",
        diseaseProtection: [],
        rootBio: [],
        pgr: [],
        seedTreatment: [],
        foliar: [],
        pestProtection: [],
      },
      {
        stageNumber: 2,
        stageNameHi: "वृद्धि foliar",
        timingHi: "20–22 DAS",
        foliar: [
          {
            kind: "foliar",
            technical: "19:19:19",
            doseHi: "1 kg",
            waterHi: "150 L पानी में",
          },
          {
            kind: "humic",
            technical: "Humic Acid",
            formulation: "Liquid 12%",
            doseHi: "250 ml",
            waterHi: "150 L पानी में",
          },
        ],
        fertilizers: [],
        pestProtection: [],
        diseaseProtection: [],
        rootBio: [],
        pgr: [],
        seedTreatment: [],
      },
      {
        stageNumber: 3,
        stageNameHi: "फूल–फली",
        timingHi: "32–35 DAS",
        foliar: [
          {
            kind: "foliar",
            technical: "0:52:34",
            doseHi: "1 kg",
            waterHi: "150 L पानी में",
          },
          {
            kind: "micronutrient",
            technical: "Boron",
            formulation: "20%",
            doseHi: "100 g",
            waterHi: "150 L पानी में",
          },
        ],
        fertilizers: [],
        pestProtection: [],
        diseaseProtection: [],
        rootBio: [],
        pgr: [],
        seedTreatment: [],
      },
      {
        stageNumber: 4,
        stageNameHi: "दाना भराव",
        timingHi: "45–50 DAS",
        foliar: [
          {
            kind: "foliar",
            technical: "SOP",
            formulation: "0:0:50",
            doseHi: "1 kg",
            waterHi: "150 L पानी में",
          },
        ],
        fertilizers: [],
        pestProtection: [],
        diseaseProtection: [],
        rootBio: [],
        pgr: [],
        seedTreatment: [],
      },
    ],
  },

  urad: {
    cropNameHi: "उड़द",
    englishName: "Black gram",
    categoryHi: "दलहन",
    totalFertilizerHi: [
      "DAP 30 kg/acre",
      "MOP 15 kg/acre",
      "S 90% 3 kg/acre",
    ],
    globalWarningsHi: [
      "SOURCE DATA — VERIFY BEFORE OPERATIONAL USE",
      "दलहन पर खड़ी फसल में यूरिया प्रसार (broadcast) मत करो — DALHAN UREA ALERT",
      "PEAK BLOOM स्प्रे समय — हल्की सिंचाई/शाम के बाद, पंखुड़ी झड़ने से बचो",
    ],
    stages: [
      {
        stageNumber: 0,
        stageNameHi: "बीज उपचार",
        timingHi: "बुवाई से पहले",
        seedTreatment: [
          {
            kind: "fungicide",
            technical: "Thiram + Carbendazim",
            doseHi: "2 g/kg बीज",
          },
          {
            kind: "insecticide",
            technical: "Thiamethoxam",
            formulation: "30% FS",
            doseHi: "2 ml/kg बीज",
          },
        ],
        mixingStatus: "seed_only",
        fertilizers: [],
        pestProtection: [],
        diseaseProtection: [],
        rootBio: [],
        pgr: [],
        foliar: [],
      },
      {
        stageNumber: 1,
        stageNameHi: "बेसल / बुवाई",
        timingHi: "बुवाई के समय",
        fertilizers: [
          {
            kind: "fertilizer",
            technical: "DAP",
            doseHi: "30 kg/acre",
          },
          {
            kind: "fertilizer",
            technical: "MOP",
            doseHi: "15 kg/acre",
          },
          {
            kind: "fertilizer",
            technical: "Sulphur",
            formulation: "90%",
            doseHi: "3 kg/acre",
          },
          {
            kind: "humic",
            technical: "Humic Acid",
            formulation: "98%",
            doseHi: "500 g/acre",
          },
        ],
        pestProtection: [],
        diseaseProtection: [],
        rootBio: [],
        pgr: [],
        seedTreatment: [],
        foliar: [],
      },
      {
        stageNumber: 2,
        stageNameHi: "वृद्धि foliar",
        timingHi: "20–25 DAS",
        foliar: [
          {
            kind: "foliar",
            technical: "19:19:19",
            doseHi: "1 kg",
            waterHi: "150 L पानी में",
          },
          {
            kind: "biostimulant",
            technical: "Seaweed Tonic",
            doseHi: "250 ml",
            waterHi: "150 L पानी में",
          },
        ],
        fertilizers: [],
        pestProtection: [],
        diseaseProtection: [],
        rootBio: [],
        pgr: [],
        seedTreatment: [],
      },
      {
        stageNumber: 3,
        stageNameHi: "फूल–फली",
        timingHi: "35 DAS",
        foliar: [
          {
            kind: "foliar",
            technical: "0:52:34",
            doseHi: "1 kg",
            waterHi: "150 L पानी में",
          },
          {
            kind: "micronutrient",
            technical: "Boron",
            formulation: "20%",
            doseHi: "100 g",
            waterHi: "150 L पानी में",
          },
        ],
        fertilizers: [],
        pestProtection: [],
        diseaseProtection: [],
        rootBio: [],
        pgr: [],
        seedTreatment: [],
      },
      {
        stageNumber: 4,
        stageNameHi: "दाना भराव",
        timingHi: "50 DAS",
        foliar: [
          {
            kind: "foliar",
            technical: "13:0:45",
            doseHi: "1 kg",
            waterHi: "150 L पानी में",
            sourceClaimHi: "स्रोत दावा: दाना रंग / चमक",
          },
        ],
        fertilizers: [],
        pestProtection: [],
        diseaseProtection: [],
        rootBio: [],
        pgr: [],
        seedTreatment: [],
      },
    ],
  },

  masoor: {
    cropNameHi: "मसूर",
    englishName: "Lentil",
    categoryHi: "दलहन",
    totalFertilizerHi: [
      "SSP 100 kg/acre (विकल्प)",
      "DAP 30 kg/acre (विकल्प)",
      "MOP 15 kg/acre",
      "S 90% 3 kg/acre",
    ],
    globalWarningsHi: [
      "SOURCE DATA — VERIFY BEFORE OPERATIONAL USE",
      "दलहन पर खड़ी फसल में यूरिया प्रसार (broadcast) मत करो — DALHAN UREA ALERT",
      "PEAK BLOOM स्प्रे समय — हल्की सिंचाई/शाम के बाद, पंखुड़ी झड़ने से बचो",
    ],
    stages: [
      {
        stageNumber: 0,
        stageNameHi: "बीज उपचार",
        timingHi: "बुवाई से पहले",
        seedTreatment: [
          {
            kind: "fungicide",
            technical: "Carbendazim + Mancozeb",
            doseHi: "2 g/kg बीज",
            brands: ["Saaf"],
          },
          {
            kind: "insecticide",
            technical: "Chlorpyrifos",
            formulation: "20% EC",
            doseHi: "2 ml/kg बीज",
          },
        ],
        mixingStatus: "seed_only",
        fertilizers: [],
        pestProtection: [],
        diseaseProtection: [],
        rootBio: [],
        pgr: [],
        foliar: [],
      },
      {
        stageNumber: 1,
        stageNameHi: "बेसल / बुवाई",
        timingHi: "बुवाई के समय",
        fertilizers: [
          {
            kind: "fertilizer",
            technical: "SSP",
            doseHi: "100 kg/acre",
            options: [
              {
                kind: "fertilizer",
                technical: "DAP",
                doseHi: "30 kg/acre",
              },
            ],
          },
          {
            kind: "fertilizer",
            technical: "MOP",
            doseHi: "15 kg/acre",
          },
          {
            kind: "fertilizer",
            technical: "Sulphur",
            formulation: "90%",
            doseHi: "3 kg/acre",
          },
          {
            kind: "humic",
            technical: "Humic Acid",
            formulation: "98%",
            doseHi: "500 g/acre",
          },
        ],
        placementHi: "फरो में",
        pestProtection: [],
        diseaseProtection: [],
        rootBio: [],
        pgr: [],
        seedTreatment: [],
        foliar: [],
      },
      {
        stageNumber: 2,
        stageNameHi: "वृद्धि foliar",
        timingHi: "30–35 DAS",
        foliar: [
          {
            kind: "foliar",
            technical: "19:19:19",
            doseHi: "1 kg",
            waterHi: "150 L पानी में",
          },
          {
            kind: "biostimulant",
            technical: "Enzyme Tonic",
            doseHi: "250 ml",
            waterHi: "150 L पानी में",
          },
        ],
        fertilizers: [],
        pestProtection: [],
        diseaseProtection: [],
        rootBio: [],
        pgr: [],
        seedTreatment: [],
      },
      {
        stageNumber: 3,
        stageNameHi: "फूल–फली",
        timingHi: "55–60 DAS",
        foliar: [
          {
            kind: "foliar",
            technical: "0:52:34",
            doseHi: "1 kg",
            waterHi: "150 L पानी में",
          },
          {
            kind: "micronutrient",
            technical: "Boron",
            formulation: "20%",
            doseHi: "100 g",
            waterHi: "150 L पानी में",
          },
        ],
        fertilizers: [],
        pestProtection: [],
        diseaseProtection: [],
        rootBio: [],
        pgr: [],
        seedTreatment: [],
      },
    ],
  },

  soybean: {
    cropNameHi: "सोयाबीन",
    englishName: "Soybean",
    categoryHi: "तिलहन / दलहन",
    totalNutrientsHi: [
      "N 12 kg/acre",
      "P₂O₅ 24 kg/acre",
      "K₂O 16 kg/acre",
      "S 10 kg/acre",
    ],
    totalFertilizerHi: [
      "DAP 40 kg/acre (विकल्प)",
      "SSP 120 kg/acre (विकल्प)",
      "MOP 25 kg/acre",
      "S 90% 8 kg/acre",
    ],
    globalWarningsHi: [
      "SOURCE DATA — VERIFY BEFORE OPERATIONAL USE",
      "PEAK BLOOM स्प्रे समय — हल्की सिंचाई/शाम के बाद, पंखुड़ी झड़ने से बचो",
      "स्रोत: बेसल में SSP preferred framing — गारंटी नहीं",
    ],
    stages: [
      {
        stageNumber: 0,
        stageNameHi: "बीज उपचार",
        timingHi: "बुवाई से पहले",
        activityHi: "बीज छाल पर कोमल उपचार",
        seedTreatment: [
          {
            kind: "fungicide",
            technical: "Penflufen + Trifloxystrobin",
            doseHi: "1 ml/kg बीज",
            brands: ["EverGol Energy"],
            noteHi: "बीज छाल पर कोमल",
          },
          {
            kind: "insecticide",
            technical: "Thiamethoxam",
            formulation: "30% FS",
            doseHi: "3 ml/kg बीज",
            targetHi: "girdle beetle / stem fly",
          },
          {
            kind: "biofertilizer",
            technical: "Rhizobium japonicum",
            doseHi: "5 g/kg बीज",
          },
        ],
        mixingStatus: "seed_only",
        fertilizers: [],
        pestProtection: [],
        diseaseProtection: [],
        rootBio: [],
        pgr: [],
        foliar: [],
      },
      {
        stageNumber: 1,
        stageNameHi: "बेसल / बुवाई",
        timingHi: "बुवाई के समय",
        fertilizers: [
          {
            kind: "fertilizer",
            technical: "SSP",
            doseHi: "120 kg/acre",
            options: [
              {
                kind: "fertilizer",
                technical: "DAP",
                doseHi: "40 kg/acre",
              },
            ],
          },
          {
            kind: "fertilizer",
            technical: "MOP",
            doseHi: "25 kg/acre",
          },
          {
            kind: "fertilizer",
            technical: "Sulphur",
            formulation: "90%",
            doseHi: "8 kg/acre",
            sourceClaimHi: "स्रोत दावा: तेल +3% का उल्लेख",
          },
          {
            kind: "humic",
            technical: "Humic Acid",
            formulation: "98%",
            doseHi: "500 g/acre",
          },
        ],
        pestProtection: [
          {
            kind: "insecticide",
            technical: "Fipronil",
            formulation: "0.3% GR",
            doseHi: "8 kg/acre",
            targetHi: "white grub",
          },
        ],
        placementHi: "बीज से 4–5 cm दूर",
        diseaseProtection: [],
        rootBio: [],
        pgr: [],
        seedTreatment: [],
        foliar: [],
      },
      {
        stageNumber: 2,
        stageNameHi: "वृद्धि foliar",
        timingHi: "25–30 DAS",
        foliar: [
          {
            kind: "foliar",
            technical: "19:19:19",
            doseHi: "1 kg",
            waterHi: "150 L पानी में",
          },
          {
            kind: "micronutrient",
            technical: "Chelated Micronutrients",
            doseHi: "200 g",
            waterHi: "150 L पानी में",
          },
          {
            kind: "humic",
            technical: "Humic Acid",
            formulation: "Liquid",
            doseHi: "250 ml",
            waterHi: "150 L पानी में",
          },
        ],
        mixingStatus: "validation",
        fieldDoctorTipHi:
          "कीटनाशक foliar केवल girdle beetle दिखने पर — लेबल/स्थानीय सलाह",
        fertilizers: [],
        pestProtection: [],
        diseaseProtection: [],
        rootBio: [],
        pgr: [],
        seedTreatment: [],
      },
      {
        stageNumber: 3,
        stageNameHi: "R1 / R2",
        timingHi: "40–45 DAS",
        foliar: [
          {
            kind: "foliar",
            technical: "0:52:34",
            doseHi: "1 kg",
            waterHi: "150 L पानी में",
          },
          {
            kind: "micronutrient",
            technical: "Boron",
            formulation: "20%",
            doseHi: "100 g",
            waterHi: "150 L पानी में",
          },
        ],
        fertilizers: [],
        pestProtection: [],
        diseaseProtection: [],
        rootBio: [],
        pgr: [],
        seedTreatment: [],
      },
      {
        stageNumber: 4,
        stageNameHi: "R5 / दाना",
        timingHi: "60–65 DAS",
        foliar: [
          {
            kind: "foliar",
            technical: "SOP",
            formulation: "0:0:50",
            doseHi: "1 kg",
            waterHi: "150 L पानी में",
            sourceClaimHi: "स्रोत दावा: bold seed / तेल",
          },
        ],
        fertilizers: [],
        pestProtection: [],
        diseaseProtection: [],
        rootBio: [],
        pgr: [],
        seedTreatment: [],
      },
    ],
  },

  mustard: {
    cropNameHi: "सरसों",
    englishName: "Mustard",
    categoryHi: "तिलहन",
    principlesHi: ["सल्फर सरसों की आत्मा है"],
    totalNutrientsHi: [
      "N 35–40 kg/acre",
      "P₂O₅ 18 kg/acre",
      "K₂O 15 kg/acre",
      "S 12 kg/acre",
    ],
    totalFertilizerHi: [
      "DAP 40 kg/acre",
      "Urea 50 kg/acre (कुल)",
      "MOP 20 kg/acre",
      "S 90% 10 kg/acre",
    ],
    globalWarningsHi: [
      "SOURCE DATA — VERIFY BEFORE OPERATIONAL USE",
      "PEAK BLOOM स्प्रे समय — हल्की सिंचाई/शाम के बाद, पंखुड़ी झड़ने से बचो",
    ],
    stages: [
      {
        stageNumber: 0,
        stageNameHi: "बीज उपचार",
        timingHi: "बुवाई से पहले",
        seedTreatment: [
          {
            kind: "fungicide",
            technical: "Metalaxyl-M",
            doseHi: "2 g/kg बीज",
            brands: ["Apron XL"],
            targetHi: "white rust",
          },
          {
            kind: "insecticide",
            technical: "Imidacloprid",
            formulation: "70% WS",
            doseHi: "5 g/kg बीज",
            targetHi: "painted bug",
          },
        ],
        mixingStatus: "seed_only",
        fertilizers: [],
        pestProtection: [],
        diseaseProtection: [],
        rootBio: [],
        pgr: [],
        foliar: [],
      },
      {
        stageNumber: 1,
        stageNameHi: "बेसल / बुवाई",
        timingHi: "बुवाई के समय",
        fertilizers: [
          {
            kind: "fertilizer",
            technical: "DAP",
            doseHi: "40 kg/acre",
          },
          {
            kind: "fertilizer",
            technical: "MOP",
            doseHi: "20 kg/acre",
          },
          {
            kind: "fertilizer",
            technical: "Urea",
            doseHi: "15 kg/acre",
          },
          {
            kind: "fertilizer",
            technical: "Sulphur",
            formulation: "90%",
            doseHi: "10 kg/acre",
          },
          {
            kind: "humic",
            technical: "Humic Acid",
            formulation: "98%",
            doseHi: "500 g/acre",
          },
        ],
        placementHi: "फरो में",
        pestProtection: [],
        diseaseProtection: [],
        rootBio: [],
        pgr: [],
        seedTreatment: [],
        foliar: [],
      },
      {
        stageNumber: 2,
        stageNameHi: "पहली सिंचाई के बाद",
        timingHi: "28–32 DAS",
        activityHi: "सिंचाई बैठने के बाद",
        fertilizers: [
          {
            kind: "fertilizer",
            technical: "Urea",
            doseHi: "35 kg/acre",
          },
          {
            kind: "micronutrient",
            technical: "Zinc sulphate",
            formulation: "33%",
            doseHi: "5 kg/acre",
          },
        ],
        pestProtection: [
          {
            kind: "insecticide",
            technical: "Fipronil",
            formulation: "0.3% GR",
            doseHi: "8 kg/acre",
            noteHi: "केवल यदि दीमक हो",
            targetHi: "दीमक",
          },
        ],
        diseaseProtection: [],
        rootBio: [],
        pgr: [],
        seedTreatment: [],
        foliar: [],
        moistureHi: "पहली सिंचाई बैठने के बाद",
      },
      {
        stageNumber: 3,
        stageNameHi: "फूल–फली",
        timingHi: "55–60 DAS",
        foliar: [
          {
            kind: "foliar",
            technical: "0:52:34",
            doseHi: "1 kg",
            waterHi: "150 L पानी में",
          },
          {
            kind: "micronutrient",
            technical: "Boron",
            formulation: "20%",
            doseHi: "150 g",
            waterHi: "150 L पानी में",
          },
        ],
        fertilizers: [],
        pestProtection: [],
        diseaseProtection: [],
        rootBio: [],
        pgr: [],
        seedTreatment: [],
      },
      {
        stageNumber: 4,
        stageNameHi: "दाना / तेल",
        timingHi: "75–80 DAS",
        foliar: [
          {
            kind: "foliar",
            technical: "13:0:45",
            doseHi: "1 kg",
            waterHi: "150 L पानी में",
            sourceClaimHi: "स्रोत दावा: frost / तेल",
          },
        ],
        fertilizers: [],
        pestProtection: [],
        diseaseProtection: [],
        rootBio: [],
        pgr: [],
        seedTreatment: [],
      },
    ],
  },

  moongfali: {
    cropNameHi: "मूंगफली",
    englishName: "Groundnut",
    categoryHi: "तिलहन",
    totalNutrientsHi: [
      "N 10 kg/acre",
      "P₂O₅ 20 kg/acre",
      "K₂O 20 kg/acre",
      "Gypsum 200 kg/acre (कुल लक्ष्य)",
    ],
    totalFertilizerHi: [
      "DAP 40 kg/acre",
      "MOP 25 kg/acre",
      "Gypsum 150–200 kg/acre",
    ],
    globalWarningsHi: [
      "SOURCE DATA — VERIFY BEFORE OPERATIONAL USE",
      "PEAK BLOOM स्प्रे समय — हल्की सिंचाई/शाम के बाद, पंखुड़ी झड़ने से बचो",
      "मूंगफली: gypsum vs sulphur — अलग उद्देश्य; स्रोत अनुसार gypsum pegging/chalky soil के लिए, sulphur substitute नहीं",
    ],
    stages: [
      {
        stageNumber: 0,
        stageNameHi: "बीज उपचार",
        timingHi: "बुवाई से पहले",
        activityHi: "बीज छाल न छिलें",
        seedTreatment: [
          {
            kind: "fungicide",
            technical: "Mancozeb",
            formulation: "75%",
            doseHi: "3 g/kg बीज",
          },
          {
            kind: "insecticide",
            technical: "Chlorpyrifos",
            formulation: "20% EC",
            doseHi: "2.5 ml/kg बीज",
          },
          {
            kind: "biofertilizer",
            technical: "Rhizobium",
            doseHi: "5 g/kg बीज",
          },
        ],
        dontHi: ["बीज की छाल न छिलें"],
        mixingStatus: "seed_only",
        fertilizers: [],
        pestProtection: [],
        diseaseProtection: [],
        rootBio: [],
        pgr: [],
        foliar: [],
      },
      {
        stageNumber: 1,
        stageNameHi: "बेसल / बुवाई",
        timingHi: "बुवाई के समय",
        fertilizers: [
          {
            kind: "fertilizer",
            technical: "DAP",
            doseHi: "40 kg/acre",
          },
          {
            kind: "fertilizer",
            technical: "MOP",
            doseHi: "25 kg/acre",
          },
          {
            kind: "fertilizer",
            technical: "Urea",
            doseHi: "10 kg/acre",
          },
          {
            kind: "humic",
            technical: "Humic Acid",
            formulation: "Granular",
            doseHi: "5 kg/acre",
          },
        ],
        pestProtection: [
          {
            kind: "insecticide",
            technical: "Thiamethoxam + Chlorantraniliprole",
            formulation: "1% + 0.5% GR",
            doseHi: "3 kg/acre",
            brands: ["Virtako"],
            targetHi: "white grub",
            noteHi: "फरो में",
          },
        ],
        placementHi: "फरो में",
        diseaseProtection: [],
        rootBio: [],
        pgr: [],
        seedTreatment: [],
        foliar: [],
      },
      {
        stageNumber: 2,
        stageNameHi: "वृद्धि foliar",
        timingHi: "20–25 DAS",
        foliar: [
          {
            kind: "foliar",
            technical: "19:19:19",
            doseHi: "1 kg",
            waterHi: "150 L पानी में",
          },
          {
            kind: "biostimulant",
            technical: "Amino Acid Tonic",
            doseHi: "250 ml",
            waterHi: "150 L पानी में",
          },
        ],
        fertilizers: [],
        pestProtection: [],
        diseaseProtection: [],
        rootBio: [],
        pgr: [],
        seedTreatment: [],
      },
      {
        stageNumber: 3,
        stageNameHi: "Pegging — सबसे महत्वपूर्ण",
        timingHi: "40–45 DAS",
        activityHi: "root zone में हल्की निराई के साथ",
        fertilizers: [
          {
            kind: "fertilizer",
            technical: "Gypsum",
            doseHi: "150–200 kg/acre",
            purposeHi: "pegging / root zone",
            sourceClaimHi: "स्रोत दावा: Ca — फली भराव / pop pods",
          },
        ],
        applicationHi: "root zone में हल्की निराई के साथ",
        fieldDoctorTipHi: "यह चरण सबसे महत्वपूर्ण — gypsum समय पर",
        foliar: [],
        pestProtection: [],
        diseaseProtection: [],
        rootBio: [],
        pgr: [],
        seedTreatment: [],
      },
      {
        stageNumber: 4,
        stageNameHi: "दाना / फली",
        timingHi: "65–70 DAS",
        foliar: [
          {
            kind: "foliar",
            technical: "SOP",
            formulation: "0:0:50",
            doseHi: "1.5 kg",
            waterHi: "150 L पानी में",
          },
          {
            kind: "micronutrient",
            technical: "Boron",
            formulation: "20%",
            doseHi: "100 g",
            waterHi: "150 L पानी में",
          },
        ],
        fertilizers: [],
        pestProtection: [],
        diseaseProtection: [],
        rootBio: [],
        pgr: [],
        seedTreatment: [],
      },
    ],
  },
};
